export const productsData = [
    {
        "product_id": 1,
        "name": "Guava Sao Paulo",
        "desc_card_simple": "La Croix | Naturally Essenced",
        "desc_card_complete": "Savor the sweet tropical delicacy and vibrant essence that satisfies your Constant Cravings !!",
        "brand": "La Croix",
        "category": "Fruits",
        "price": 8.99,
        "image_sm": "https://ohv-store-v2.netlify.app/images/sm-product-laCriox-Guava-Sao.png",
        "image_md": "https://ohv-store-v2.netlify.app/images/md-product-la-criox-guava.png",
        "image_lg": "https://ohv-store-v2.netlify.app/images/lg-product-la-croix-guava.png",
        "rating": "5/5"
    },
    {
        "product_id": 2,
        "name": "Orange Cream",
        "desc_card_simple": "Olipop | Sparkling Tonic",
        "desc_card_complete": "Creamy, vanilla goodness and a bright pop of tangerine and mandarin citrus join forces to bring back this iconic childhood treat.",
        "brand": "Olipop",
        "category": "Fruits",
        "price": 4.29,
        "image_sm": "https://ohv-store-v2.netlify.app/images/sm-product-olipop-orange-cream.png",
        "image_md": "https://ohv-store-v2.netlify.app/images/md-product-olipop-orange-cream.png",
        "image_lg": "https://ohv-store-v2.netlify.app/images/lg-product-olipop-orange-cream.png",
        "rating": "5/5"
    },
    {
        "product_id": 3,
        "name": "Tropical Punch",
        "desc_card_simple": "Olipop | Sparkling Tonic",
        "desc_card_complete": "Like a vacation for your tastebuds, Tropical Punch perfectly balances pineapple, passion fruit, mandarine, and apple juices for a crisp, juicy and nostalgic flavor reminiscent of your favorite childhood fruit punch.",
        "brand": "Olipop",
        "category": "Fruits",
        "price": 4.29,
        "image_sm": "https://ohv-store-v2.netlify.app/images/sm-product-olipop-tropical-punch.png",
        "image_md": "https://ohv-store-v2.netlify.app/images/md-product-olipop-tropical-punch.png",
        "image_lg": "https://ohv-store-v2.netlify.app/images/lg-product-olipop-tropical-punch.png",
        "rating": "5/5"
    },
    {
        "product_id": 4,
        "name": "Banana Cream",
        "desc_card_simple": "Olipop | A New Kind of Soda",
        "desc_card_complete": "Never thought you see us make a banana cream soda? Candidly, neither did we. But, inspired by the mischievous and joyous energy of the Minions, we felt emboldened to play with the idea!",
        "brand": "Olipop",
        "category": "Fruits",
        "price": 4.29,
        "image_sm": "https://ohv-store-v2.netlify.app/images/sm-product-olipop-banana-cream.png",
        "image_md": "https://ohv-store-v2.netlify.app/images/md-product-olipop-banana-cream.png",
        "image_lg": "https://ohv-store-v2.netlify.app/images/lg-product-olipop-banana-cream.png",
        "rating": "5/5"
    },
    {
        "product_id": 5,
        "name": "Matcha Latte",
        "desc_card_simple": "Taika | Matcha Perfected",
        "desc_card_complete": "A deliciously creamy matcha made in heaven, canned in space and ready for you to drink, right here on planet Earth. Hours of creativity in a can.",
        "brand": "Taika",
        "category": "Coffee",
        "price": 3.59,
        "image_sm": "https://ohv-store-v2.netlify.app/images/sm-product-taika-matcha-latte.png",
        "image_md": "https://ohv-store-v2.netlify.app/images/md-product-taika-matcha-latte.png",
        "image_lg": "https://ohv-store-v2.netlify.app/images/lg-product-taika-product-matcha-latte.png",
        "rating": "5/5"
    },
    {
        "product_id": 6,
        "name": "Macadamia Latte",
        "desc_card_simple": "Taika | Latte Perfected",
        "desc_card_complete": "The word macadamia is dangerously close to the word macarena, but we are here for it. This latte tastes like coffee ice cream but with zero sugar.",
        "brand": "Taika",
        "category": "Coffee",
        "price": 3.49,
        "image_sm": "https://ohv-store-v2.netlify.app/images/sm-product-taika-maca-latte.png",
        "image_md": "https://ohv-store-v2.netlify.app/images/md-product-taika-maca-latte.png",
        "image_lg": "https://ohv-store-v2.netlify.app/images/lg-product-taika-maca-latte.png",
        "rating": "5/5"
    },
    {
        "product_id": 7,
        "name": "Black Coffee",
        "desc_card_simple": "Taika | Coffee Perfected",
        "desc_card_complete": "For many, coffee is meant to be black. No sugar, no milk, no frills. And that is just what we have done while delivering our Taika twist on a classic.",
        "brand": "Taika",
        "category": "Coffee",
        "price": 3.29,
        "image_sm": "https://ohv-store-v2.netlify.app/images/sm-product-taika-black-coffee.png",
        "image_md": "https://ohv-store-v2.netlify.app/images/md-product-taika-black-coffee.png",
        "image_lg": "https://ohv-store-v2.netlify.app/images/lg-product-taika-black-coffee.png",
        "rating": "5/5"
    },
    {
        "product_id": 8,
        "name": "Oat Milk Latte",
        "desc_card_simple": "Taika | Coffee Perfected",
        "desc_card_complete": "Oatmeal is boring. Our oat milk latte is not. Lightly sweet but without any added sugar, its smooth like a dolphin and delicious like cereal milk.",
        "brand": "Taika",
        "category": "Coffee",
        "price": 3.69,
        "image_sm": "https://ohv-store-v2.netlify.app/images/sm-product-taika-oatmilk-latte.png",
        "image_md": "https://ohv-store-v2.netlify.app/images/md-product-taika-oatmilk.png",
        "image_lg": "https://ohv-store-v2.netlify.app/images/lg-product-taika-oatmilk-latte.png",
        "rating": "5/5"
    },
    {
        "product_id": 9,
        "name": "White Peach",
        "desc_card_simple": "Calpico | Peach Perfect",
        "desc_card_complete": "Oatmeal is boring. Our oat milk latte is not. Lightly sweet but without any added sugar, its smooth like a dolphin and delicious like cereal milk.",
        "brand": "Calpico",
        "category": "Milky",
        "price": 3.69,
        "image_sm": "https://ohv-store-v2.netlify.app/images/sm-product-calpico-white-peach.png",
        "image_md": "https://ohv-store-v2.netlify.app/images/md-product-calpico-white-peach.png",
        "image_lg": "https://ohv-store-v2.netlify.app/images/lg-product-calpico-white-peach.png",
        "rating": "5/5"
    },
    {
        "product_id": 10,
        "name": "Calpico Mango",
        "desc_card_simple": "Calpico | Amazing Mango Flavor",
        "desc_card_complete": "Oatmeal is boring. Our oat milk latte is not. Lightly sweet but without any added sugar, its smooth like a dolphin and delicious like cereal milk.",
        "brand": "Taika",
        "category": "Coffee",
        "price": 3.69,
        "image_sm": "https://ohv-store-v2.netlify.app/images/sm-product-calpico-mango.png",
        "image_md": "https://ohv-store-v2.netlify.app/images/md-product-calpico-mango.png",
        "image_lg": "https://ohv-store-v2.netlify.app/images/lg-product-calprico-mango.png",
        "rating": "5/5"
    },
    {
        "product_id": 11,
        "name": "Calpico Melon",
        "desc_card_simple": "Calpico | Amazing Melon Flavor",
        "desc_card_complete": "Oatmeal is boring. Our oat milk latte is not. Lightly sweet but without any added sugar, its smooth like a dolphin and delicious like cereal milk.",
        "brand": "Taika",
        "category": "Coffee",
        "price": 3.69,
        "image_sm": "https://ohv-store-v2.netlify.app/images/sm-product-calpico-melon.png",
        "image_md": "https://ohv-store-v2.netlify.app/images/md-product-calpico-melon.png",
        "image_lg": "https://ohv-store-v2.netlify.app/images/lg-product-calpico-melon.png",
        "rating": "5/5"
    },
    {
        "product_id": 12,
        "name": "Calpico Strawberry",
        "desc_card_simple": "Calpico | Strawberry Flavor",
        "desc_card_complete": "Oatmeal is boring. Our oat milk latte is not. Lightly sweet but without any added sugar, its smooth like a dolphin and delicious like cereal milk.",
        "brand": "Taika",
        "category": "Coffee",
        "price": 3.69,
        "image_sm": "https://ohv-store-v2.netlify.app/images/sm-product-calpico-strawberry.png",
        "image_md": "https://ohv-store-v2.netlify.app/images/md-product-calpico-strawberry.png",
        "image_lg": "https://ohv-store-v2.netlify.app/images/lg-product-calpico-strawberry.png",
        "rating": "5/5"
    }
]